(define-module (tests box-demo-assert)
  #:use-module (icnu eval)
  #:use-module (icnu icnu)
  #:use-module (icnu rewrite)
  #:use-module (icnu utils format)
  #:export (assert-box-demo!))

(define (assert-box-demo! file)
  ;; box-demo는 구조적 재작성(AC/AA 등) 전 단계의 값 전파 경로를 이용해 검증한다.
  ;; 따라서 passes를 const-fold + if-fold까지만 제한해 연결성을 보존한다.
  (let* ((opts1 '((out-name . out1) (out-port . l)
                  (passes . (rewrite-pass-const-fold! rewrite-pass-if-fold!))
                  (max-iter . 50)))
         (opts2 '((out-name . out2) (out-port . l)
                  (passes . (rewrite-pass-const-fold! rewrite-pass-if-fold!))
                  (max-iter . 50)))
         (v1 (eval-icnu-file file opts1))
         (v2 (eval-icnu-file file opts2)))
    (unless (and (number? v1) (= v1 15))
      (error "box-demo: expected out1=15" v1))
    (unless (and (number? v2) (= v2 100))
      (error "box-demo: expected out2=100" v2))
    (format-string #t "box-demo assertions passed: out1=~a, out2=~a\n" v1 v2)
    #t))
