;;; Interpreter + Examples tests (auto-discover .icnu files in examples/)

(define-module (tests interpreter-tests)
  #:use-module (ice-9 match)
  #:use-module (ice-9 ftw)
  #:use-module (icnu utils format)
  #:use-module (icnu utils assertions)
  #:use-module (icnu eval)
  #:use-module (icnu icnu)
  #:use-module (icnu tools icnu-proof)
  #:export (run-all-tests))

(define (string-suffix? s suf)
  (let ((ls (string-length s)) (lf (string-length suf)))
    (and (>= ls lf) (string=? suf (substring s (- ls lf) ls)))))

(define (read-sexp-string path)
  (call-with-input-file path
    (lambda (port)
      (let ((sexpr (read port)))
        (format-string #f "~a" sexpr)))))

(define (eval-file path . maybe-opts)
  (let* ((opts (if (null? maybe-opts) '() (car maybe-opts)))
         (src (read-sexp-string path)))
    (apply eval-icnu-string (cons src (if (null? maybe-opts) '() maybe-opts)))))

(define (expected-result-for-path path)
  (cond
   ((string-suffix? path "add-demo.icnu") 42)
   ((string-suffix? path "add-int-real.icnu") 3.5)
   ((string-suffix? path "eq-fold.icnu") 1)
   ((string-suffix? path "l2-if-true.icnu") 10)
   ((string-suffix? path "if-true.icnu") 1)
   ((string-suffix? path "l2-add.icnu") 15)
   ((string-suffix? path "unit-inc.icnu") 10)
   ((string-suffix? path "unit-sum1.icnu") 15)
   ((string-suffix? path "all-arith-if.icnu") 42)
   ((string-suffix? path "all-cons-first-rest.icnu") 1)
   ((string-suffix? path "all-pure-pair.icnu") 15)
   (else #f)))

(define (file-has-out? path)
  (let* ((src (read-sexp-string path))
         (net (parse-icnu-string-to-net src)))
    (and (node-agent net 'out) #t)))

(define (list-example-icnu-files)
  (let ((all (scandir "examples")))
    (map (lambda (name) (string-append "examples/" name))
         (filter (lambda (name)
                   (and (not (or (string=? name ".") (string=? name "..")))
                        (string-suffix? name ".icnu")))
                 all))))

(define (test-one-example path)
  (if (file-has-out? path)
      (let* ((res (eval-file path '((out-name . out) (out-port . p))))
             (expected (expected-result-for-path path)))
        (if expected
            (begin
              (assert-eq res expected (format-string #f "~a should evaluate to ~a" path expected))
              (format-string #t " - ~a => ~a ... ok~% " path res)
              #t)
            (begin
              (assert-true (not (eq? res 'icnu-unresolved))
                           (format-string #f "~a should resolve an out value" path))
              (format-string #t " - ~a => ~a ... ok~% " path res)
              #t)))
      (let* ((src (read-sexp-string path))
             (ok (run-steps-on-string src 10)))
        (assert-true ok (format-string #f "~a should step without error" path))
        (format-string #t " - ~a (stepping) ... ok~% " path)
        #t)))

(define (run-all-tests)
  (format-string #t "~%--- Running tests/interpreter-tests.scm ---~%~%")
  (format-string #t "Running Interpreter tests (auto .icnu discovery)...~%")
  (let ((files (list-example-icnu-files)))
    (for-each
     (lambda (f)
       (test-one-example f))
     files))
  (format-string #t "~%All Interpreter tests completed successfully.~%")
  #t)

(run-all-tests)
