(define-module (icnu tools icnu-small-steps)
  #:use-module (icnu utils format)
  #:use-module (icnu utils strings)
  #:use-module (icnu tools icnu-proof)
  #:export (small-steps-output small-steps-output-with-limit))

(define (small-steps-output src)
  (small-steps-output-with-limit src 100))

(define (small-steps-output-with-limit src max-steps)
  (let ((seq (small-step-sequence-string src max-steps)))
    (let loop ((lst seq) (i 1) (acc '()))
      (if (null? lst)
          (string-append (string-join-list (reverse acc) "\n")
                         (if (null? acc) "" "\n"))
          (let ((header (format-string #f ";; STEP ~a" i))
                (body (car lst)))
            (loop (cdr lst) (+ i 1) (cons body (cons header acc))))))))
