(define-module (icnu tools icnu-run)
  #:use-module (ice-9 match)
  #:use-module (icnu eval)
  #:use-module (icnu utils format)
  #:use-module (icnu utils log)
  #:export (main))

(define (read-all path)
  (call-with-input-file path
    (lambda (port)
      (let ((sexpr (read port)))
        (format-string #f "~a" sexpr)))))

(define (parse-port s)
  (cond
   ((or (eq? s 'p) (string=? s "p")) 'p)
   ((or (eq? s 'l) (string=? s "l")) 'l)
   ((or (eq? s 'r) (string=? s "r")) 'r)
   (else 'p)))

(define (usage prog)
  (format-string #t "Usage: ~a <file.icnu> [out-name] [out-port]\n" prog)
  (format-string #t "  Example: ~a examples/add-demo.icnu out p\n" prog)
  #f)

(define (main args)
  (match (cdr args)
    ((file)
     (let* ((src (read-all file))
            (result (eval-icnu-string src)))
       (format-string #t "~a~%" result)
       #t))
    ((file out-name)
     (let* ((src (read-all file))
            (out-sym (string->symbol out-name))
            (result (eval-icnu-string src `((out-name . ,out-sym)))))
       (format-string #t "~a~%" result)
       #t))
    ((file out-name out-port)
     (let* ((src (read-all file))
            (out-sym (string->symbol out-name))
            (port (parse-port out-port))
            (result (eval-icnu-string src `((out-name . ,out-sym) (out-port . ,port)))))
       (format-string #t "~a~%" result)
       #t))
    (else (usage (car args)))))

;; script entry point
(main (program-arguments))
