(define-module (icnu ic-rewrite)
  #:use-module (icnu utils internal)
  #:use-module (icnu utils compat)
  #:use-module (icnu utils strings)
  #:use-module (ice-9 match)
  #:use-module (icnu utils format)
  #:use-module (icnu utils log)
  #:use-module (icnu icnu)
  #:use-module ((icnu literals) #:prefix lit:)
  #:export (rewrite-pass-AC!
            rewrite-pass-AE!
            rewrite-pass-wire-cleanup!
            rewrite-pass-AA-merge!
            rewrite-pass-CE-annihilation!
            is-literal-node?
            get-literal-value))

;; Pure-IC helpers bridged from literals
(define (is-literal-node? net node-name)
  (lit:ic-literal? net node-name))

(define (get-literal-value net node-name)
  (lit:ic-literal-value net node-name))

;; Structural rewrite rules (pure IC)

(define (rule-AA! net a-name b-name pass-through?)
  (when (and (eq? (node-agent net a-name) 'A)
             (eq? (node-agent net b-name) 'A))
    (debugf 1 "rule-AA!: attempting on ~a and ~a\n" a-name b-name)
    (let* ((a_p (cons a-name 'p)) (a_l (cons a-name 'l)) (a_r (cons a-name 'r))
           (b_p (cons b-name 'p)) (b_l (cons b-name 'l)) (b_r (cons b-name 'r))
           (P_al (peer net a_l))
           (P_ar (peer net a_r))
           (P_bl (peer net b_l))
           (P_br (peer net b_r))
           (a-is-lit (is-literal-node? net a-name))
           (b-is-lit (is-literal-node? net b-name)))
      (cond
       (pass-through?
        (debugf 2 "rule-AA!: skipping on ~a and ~a (pass-through: ~a)\n" a-name b-name pass-through?)
        #f)
       ((or a-is-lit b-is-lit)
        #f)
       (else
        (let* ((n_sym (make-fresh-name net "a"))
               (n_p (cons n_sym 'p)) (n_l (cons n_sym 'l)) (n_r (cons n_sym 'r)))
          (add-node! net n_sym 'A)
          (inherit-nu! net n_sym a-name b-name)
          (unmark-nu! net a-name)
          (unmark-nu! net b-name)
          (unlink-port! net a_p) (unlink-port! net a_l) (unlink-port! net a_r)
          (unlink-port! net b_l) (unlink-port! net b_r)
          (when (and P_al P_bl) (link-peers! net P_al P_bl))
          (when P_ar (link-peers! net P_ar n_r))
          (when P_br (link-peers! net P_br n_l))
          (delete-node! net a-name)
          (delete-node! net b-name)
          (debugf 1 "rule-AA!: applied on ~a and ~a, created ~a\n" a-name b-name n_sym)
          #t))))))

(define (rule-AC! net a-name c-name)
  (if (and (eq? (node-agent net a-name) 'A)
           (eq? (node-agent net c-name) 'C))
      (let ((c-p-peer (peer net (cons c-name 'p))))
        (when (equal? c-p-peer (cons a-name 'p))
          (let ((c-l-peer (peer net (cons c-name 'l)))
                (c-r-peer (peer net (cons c-name 'r)))
                (a-l (cons a-name 'l))
                (a-r (cons a-name 'r)))
            (when c-l-peer (rewire! net c-l-peer a-l))
            (when c-r-peer (rewire! net c-r-peer a-r))
            (unlink-port! net (cons a-name 'p))
            (delete-node! net c-name)
            (debugf 1 "rule-AC!: applied on ~a and ~a\n" a-name c-name)
            #t)))
      #f))

(define (rule-AE! net a-name e-name)
  (if (and (eq? (node-agent net a-name) 'A) (eq? (node-agent net e-name) 'E))
      (let ((e-p-peer (peer net (cons e-name 'p))))
        (when (equal? e-p-peer (cons a-name 'p))
          (delete-node! net a-name)
          (delete-node! net e-name)
          (debugf 1 "rule-AE!: applied on ~a and ~a\n" a-name e-name)
          #t))
      #f))

(define (rule-CE! net c-name e-name)
  (if (and (eq? (node-agent net c-name) 'C) (eq? (node-agent net e-name) 'E))
      (let ((e-p-peer (peer net (cons e-name 'p))))
        (when (equal? e-p-peer (cons c-name 'p))
          (delete-node! net c-name)
          (delete-node! net e-name)
          (debugf 1 "rule-CE!: applied on ~a and ~a\n" c-name e-name)
          #t))
      #f))

(define (skip-AC? net c)
  (let ((p (peer net (cons c 'p)))
        (l (peer net (cons c 'l)))
        (r (peer net (cons c 'r))))
    (or (and p (eq? 'prim/if (node-tag net (car p))))
        (and l (eq? 'prim/if (node-tag net (car l))))
        (and r (eq? 'prim/if (node-tag net (car r)))))))

(define (rewrite-pass-AC! net)
  (let ((changed? #f)
        (pairs (find-active-pairs net)))
    (for-each
     (lambda (pair)
       (match pair
         (((a . 'A) (c . 'C))
          (let ((skip? (skip-AC? net c)))
            (unless skip?
              (when (rule-AC! net a c)
                (set! changed? #t)))))
         (((c . 'C) (a . 'A))
          (let ((skip? (skip-AC? net c)))
            (unless skip?
              (when (rule-AC! net a c)
                (set! changed? #t)))))
         (_ #f)))
     pairs)
    changed?))

(define (rewrite-pass-AE! net)
  (let ((changed? #f)
        (pairs (find-active-pairs net)))
    (for-each
     (lambda (pair)
       (match pair
         (((a . 'A) (e . 'E))
          (when (rule-AE! net a e)
            (set! changed? #t)))
         (((e . 'E) (a . 'A))
          (when (rule-AE! net a e)
            (set! changed? #t)))
         (_ #f)))
     pairs)
    changed?))


(define (rewrite-pass-wire-cleanup! net)
  (let ((changed? #f))
    (for-each
     (lambda (c)
       (let ((p (peer net (cons c 'p)))
             (l (peer net (cons c 'l)))
             (r (peer net (cons c 'r))))
         (when (and (not p) (not l) (not r))
           (delete-node! net c)
           (set! changed? #t))))
     (all-nodes-with-agent net 'C))
    changed?))

(define (rewrite-pass-AA-merge! net)
  (let ((changed? #f)
        (pairs (find-active-pairs net)))
    (for-each
     (lambda (pair)
       (match pair
         (((a . 'A) (b . 'A))
          (let ((ta (node-tag net a)) (tb (node-tag net b)))
            (unless (or (eq? ta 'user/output) (eq? tb 'user/output))
              (when (rule-AA! net a b #f)
                (set! changed? #t)))))
         (_ #f)))
     pairs)
    changed?))

(define (rewrite-pass-CE-annihilation! net)
  (let ((changed? #f)
        (pairs (find-active-pairs net)))
    (for-each
     (lambda (pair)
       (match pair
         (((c . 'C) (e . 'E))
          (when (rule-CE! net c e) (set! changed? #t)))
         (((e . 'E) (c . 'C))
          (when (rule-CE! net c e) (set! changed? #t)))
         (_ #f)))
     pairs)
    changed?))
