(define-module (icnu literals)
  #:use-module ((icnu ic) #:prefix ic:)
  #:export (ic-literal? ic-literal-type ic-literal-value ic-make-literal-node!))

(define (ic-literal? net name)
  (let ((tag (ic:node-tag net name)))
    (memq tag '(lit/num lit/int lit/real lit/char lit/str lit/symbol))))

(define (ic-literal-type net name)
  (let ((tag (ic:node-tag net name)))
    (cond
     ((or (eq? tag 'lit/int) (eq? tag 'lit/num)) 'int)
     ((eq? tag 'lit/real)   'real)
     ((eq? tag 'lit/char)   'char)
     ((eq? tag 'lit/str)    'str)
     ((eq? tag 'lit/symbol) 'symbol)
     (else 'unknown))))

(define (ic-literal-value net name)
  (if (ic-literal? net name)
      (let ((meta (ic:node-meta net name)))
        (cond
         ((and (pair? meta) (eq? (car meta) 'quote))
          (cadr meta))
         ((list? meta)
          (let ((p (assq 'value meta)))
            (if p (cdr p) meta)))
         (else meta)))
      name))

(define (ic-make-literal-node! net name lit-tag lit-val)
  (ic:add-node! net name 'A)
  (ic:set-node-tag! net name lit-tag)
  (ic:set-node-meta! net name lit-val)
  net)
