(define-module (icnu literals)
  #:use-module ((icnu ic) #:prefix ic:)
  #:use-module (icnu utils internal)
  #:use-module (ice-9 match)
  #:export (ic-literal? ic-literal-value ic-make-literal-node!))

(define (ic-literal? net name)
  (let ((tag (ic:node-tag net name)))
    (memq tag '(lit/bool lit/num lit/str lit/pair))))

(define (ic-literal-value net name)
  (if (ic-literal? net name)
      (let ((meta (ic:node-meta net name)))
        (cond
         ((and (pair? meta) (eq? (car meta) 'quote))
          (cadr meta))
         ((and (list? meta) (pair? meta) (pair? (car meta)))
          (let ((p (assq 'value meta)))
            (if p (cdr p) meta)))
         (else meta)))
      name))

(define (ic-make-literal-node! net name lit-tag lit-val)
  (ic:add-node! net name 'A)
  (ic:set-node-tag! net name lit-tag)
  (ic:set-node-meta! net name lit-val)
  net)
